# Generated by Django 5.2.15 on 2026-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_update_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('notice', 'Notice'), ('event', 'Event'), ('placement', 'Placement'), ('recruiter', 'Recruiter'), ('gallery', 'Gallery'), ('faculty', 'Faculty'), ('testimonial', 'Testimonial'), ('course', 'Course'), ('student_life', 'Student Life'), ('about', 'About'), ('stats', 'Stats'), ('unique_feature', 'Unique Feature')], default='notice', max_length=32),
        ),
        migrations.AddIndex(
            model_name='update',
            index=models.Index(fields=['section', '-created_at'], name='updates_upd_section_000599_idx'),
        ),
    ]
