# Generated by Django 6.0.6 on 2026-07-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_update_section_update_updates_upd_section_000599_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Package in LPA (e.g., 12.50)', max_digits=5)),
                ('photo', models.ImageField(blank=True, help_text='Optional student photo', null=True, upload_to='placements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-package_lpa', '-created_at'],
                'indexes': [models.Index(fields=['-package_lpa'], name='updates_stu_package_5dbab7_idx')],
            },
        ),
    ]
