# Generated by Django 5.2.15 on 2026-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_studentplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('notice', 'Notice'), ('event', 'Event'), ('placement', 'Placement'), ('recruiter', 'Recruiter'), ('gallery', 'Gallery'), ('faculty', 'Faculty'), ('testimonial', 'Testimonial'), ('course', 'Course'), ('student_life', 'Student Life'), ('about', 'About'), ('stats', 'Stats'), ('unique_feature', 'Unique Feature'), ('campus', 'Campus')], default='notice', max_length=32),
        ),
    ]
