# Generated by Django 6.0.6 on 2026-08-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_alter_update_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF or document attachment.', null=True, upload_to='updates/attachments/'),
        ),
    ]
