upstream api {
    server api:8000;
}

server {
    listen 80;
    server_name localhost;

    # Gzip settings
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;

    # Serve compiled static frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy Django API requests
    location /api/ {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    # Proxy Django Admin requests
    location /admin/ {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    # Serve Django media & static files if needed
    location /django_static/ {
        alias /app/staticfiles/;
    }

    location /django_media/ {
        alias /app/media/;
    }
}
