# Generated by Django 6.0.6 on 2026-07-29 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Package in LPA (e.g., 12.50)', max_digits=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='placements/')),
                ('year', models.IntegerField(default=2024)),
                ('branch', models.CharField(default='CSE', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-package_lpa', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='placement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='placement',
            name='students_placed',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_or_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(default='Main Auditorium', max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(default='Notice', max_length=100),
        ),
        migrations.AlterField(
            model_name='placement',
            name='recruiters',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='placement',
            name='training_hours',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='placement',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='metadata',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
