# Generated by Django 6.0.6 on 2026-08-05 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litam', '0002_studentplacement_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='Campus', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/campus/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Campus Gallery',
                'verbose_name_plural': 'Campus Gallery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='Student Life', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/students/')),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Student Gallery',
                'verbose_name_plural': 'Student Gallery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('notice', 'Notice'), ('event', 'Event'), ('placement', 'Placement'), ('recruiter', 'Recruiter'), ('gallery', 'Gallery'), ('faculty', 'Faculty'), ('testimonial', 'Testimonial'), ('course', 'Course'), ('student_life', 'Student Life'), ('about', 'About'), ('stats', 'Stats'), ('unique_feature', 'Unique Feature'), ('campus', 'Campus')], default='notice', max_length=32)),
                ('title', models.CharField(help_text='Short headline for the update.', max_length=200)),
                ('message', models.TextField(help_text='Message or content for the update.')),
                ('image', models.ImageField(blank=True, help_text='Optional image.', null=True, upload_to='updates/')),
                ('attachment', models.FileField(blank=True, help_text='Optional document attachment.', null=True, upload_to='updates/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='course_of_interest',
            field=models.CharField(blank=True, default='General Inquiry', max_length=255),
        ),
    ]
