# Generated by Django 6.0.6 on 2026-08-15 14:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litam', '0003_campusgallery_studentgallery_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document attachment.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='updates/attachments/'),
        ),
    ]
