# Generated by Django 6.0.6 on 2026-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litam', '0004_alter_update_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='section',
            field=models.CharField(choices=[('notice', 'Notice'), ('event', 'Event')], default='notice', max_length=32),
        ),
    ]
